#!/usr/bin/env bash
# One-shot: generate TLS certs, create the API user, seed BIN001..BIN008
# device credentials, and write everything to mosquitto/passwd and .env.secrets.
#
# Safe to re-run: certs are kept if present; passwd users are overwritten
# with fresh passwords each time (change SEED_DEVICES if you want different IDs).
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
SCRIPTS="$ROOT/scripts"
SECRETS_FILE="$ROOT/.env.secrets"
SEED_DEVICES=(BIN001 BIN002 BIN003 BIN004 BIN005 BIN006 BIN007 BIN008)

echo "── 1/3  Generating TLS certificates ────────────────────────"
"$SCRIPTS/gen_certs.sh"
echo

echo "── 2/3  Creating API + shared devices users ─────────────────"
API_USER="api"
API_PASS="$(openssl rand -base64 24 | tr -d '=+/' | cut -c1-24)"
"$SCRIPTS/add_device.sh" "$API_USER" "$API_PASS" >/dev/null

DEVICES_USER="devices"
DEVICES_PASS="$(openssl rand -base64 24 | tr -d '=+/' | cut -c1-24)"
"$SCRIPTS/add_device.sh" "$DEVICES_USER" "$DEVICES_PASS" >/dev/null

# Persist credentials for docker-compose (API) and for flashing ESP32s (devices).
umask 077
cat > "$SECRETS_FILE" <<EOF
# Auto-generated by scripts/bootstrap.sh — do not commit.
MQTT_USERNAME=$API_USER
MQTT_PASSWORD=$API_PASS
DEVICES_PASSWORD=$DEVICES_PASS
EOF
echo "  ✓ api / $API_PASS"
echo "  ✓ devices / $DEVICES_PASS   ← paste this into firmware/SmartBinNode/config.h"
echo "  (both written to $SECRETS_FILE)"
echo

echo "── 3/3  Seeding device credentials ─────────────────────────"
for dev in "${SEED_DEVICES[@]}"; do
  "$SCRIPTS/add_device.sh" "$dev"
  echo
done

echo "════════════════════════════════════════════════════════════"
echo "Bootstrap complete."
echo "Next: docker compose up -d"
echo "Then: python -m simulator.sim --seed   (registers bins in the DB)"
echo "════════════════════════════════════════════════════════════"
